### ISSUE TITLE
internal server error from user-administration view

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodsoft#798]
I have not been able to reproduce it on my own yet. Here is an excerpt from a production system. It appeared around `2021-01-02T11:29:30.346621`.
```
> ActionView::Template::Error (undefined method `association' for nil:NilClass):
> 12:       %th= heading_helper User, :last_activity
> 13:       %th(colspan="2")= t 'ui.actions'
> 14:   %tbody
> 15:     - for user in @users
> 16:       %tr
> 17:         %td= link_to show_user(user), [:admin, user]
> 18:         - if FoodsoftConfig[:use_nick]
> app/views/admin/users/_users.html.haml:15
```

**Comment by wvengen** [comment]
Hmm that's weird. Apparently `@users` could not be loaded. It is set [here](https://github.com/foodcoops/foodsoft/blob/master/app/controllers/admin/users_controller.rb#L4).
Could it be that `natural_search` or pagination has issues?

**Comment by JuliusR** [comment]
I believe that `@users` is properly set, but one of the users causes some inner code to fail. Since the error reporting is not perfect, it blaims that line. I asked the original reporter to perform some tests. You received a copy of my email.

**Comment by RelevanterUsername** [comment]
Hi Julius, 
I checked the links you provided me via e-mail while being logged in.
The set of links to the first 5 pages of the user list did work, while the last link returned an internal server error.
I hope this helps, please come back to me if there is something else I should test.
Kind regards
David

**Comment by JuliusR** [comment]
For the record: these are the five pages that are working
```
/NAME_OF_FOODCOOP/admin/users?page=1&per_page=1
/NAME_OF_FOODCOOP/admin/users?page=2&per_page=1
/NAME_OF_FOODCOOP/admin/users?page=3&per_page=1
/NAME_OF_FOODCOOP/admin/users?page=4&per_page=1
/NAME_OF_FOODCOOP/admin/users?page=5&per_page=1
```
, and the failing page is
```
/NAME_OF_FOODCOOP/admin/users?page=1&per_page=0
```

**Comment by JuliusR** [comment]
@RelevanterUsername it is good that the first 5 pages are working. You should see 1 user per page. Let us find the exact user that causes the error in the admin view (not his personal fault, though). The first page fails for you if you are showing 20 users per page (the default). The first 5 users are fine, so could you please check the remaining 15 users? I will send you personalized links by email.

**Comment by JuliusR** [comment]
@wvengen: I could reproduce a problem on the `rails console`.

The following code (taken from [here](https://github.com/foodcoops/foodsoft/blob/a32319572f8638d20aa52acae5f54c1da68667d1/app/controllers/admin/users_controller.rb#L11)) fails at page `14`
```
(13..15).each{|i| puts User.undeleted.includes(:mail_delivery_status).natural_order.page(i).per(1).first.inspect }
```
, but the following code works fine
```
(13..15).each{|i| puts User.undeleted.natural_order.page(i).per(1).first.inspect }
```
Looking at that User I noticed a case mismatch of the mail address:
```
irb(main):078:0> User.undeleted.natural_order.page(14).per(1).first.email
=> # [email address with lowercase first letter]
irb(main):079:0> User.undeleted.natural_order.page(14).per(1).first.mail_delivery_status.first.email[0]
=> # [email address with UPPERCASE first letter]
```
I believe that is the problem here. Users and mail delivery status are joined by email address.

**Comment by RelevanterUsername** [comment]
Hi Julius,
I checked the new links and one of them is not working. It is the middle one, which is linked to the user Helge (probably, of course I did not see it, because the link does not work, but the other two are correctly named).
Regards 
David

**Comment by JuliusR** [comment]
> I checked the new links and one of them is not working. It is the middle one,

OK, great. We found the problem then: case mismatch of email address.

As a temporary workaround, you @RelevanterUsername can perform user administration using the following entry points:
```
/NAME_OF_FOODCOOP/admin/users?page=1&per_page=13
/NAME_OF_FOODCOOP/admin/users?page=2&per_page=14
```
The first link shows all users before the problematic one, and the second link shows 14 users immediately after the problematic one. Starting from the second link, you should be able to use the links to follow-up pages. Should I send you personalized links by email?

**Comment by JuliusR** [comment]
The collation of primary-key and foreign-key columns may be relevant here.
```
MariaDB [(none)]> SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE schema_name = 'NAME_OF_FOODCOOP';
+--------------+----------------+----------------------------+------------------------+----------+
| CATALOG_NAME | SCHEMA_NAME    | DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME | SQL_PATH |
+--------------+----------------+----------------------------+------------------------+----------+
| def          | NAME_OF_FOODCOOP | utf8mb4                    | utf8mb4_unicode_520_ci | NULL     |
+--------------+----------------+----------------------------+------------------------+----------+
1 row in set (0.001 sec)
MariaDB [(none)]> SELECT column_name, character_set_name, collation_name from information_schema.columns WHERE table_schema='NAME_OF_FOODCOOP' AND table_name = 'users';
+------------------------+--------------------+-----------------+
| column_name            | character_set_name | collation_name  |
+------------------------+--------------------+-----------------+
| id                     | NULL               | NULL            |
| nick                   | utf8               | utf8_general_ci |
| password_hash          | utf8               | utf8_general_ci |
| password_salt          | utf8               | utf8_general_ci |
| first_name             | utf8               | utf8_general_ci |
| last_name              | utf8               | utf8_general_ci |
| email                  | utf8               | utf8_general_ci |
| phone                  | utf8               | utf8_general_ci |
| created_on             | NULL               | NULL            |
| reset_password_token   | utf8               | utf8_general_ci |
| reset_password_expires | NULL               | NULL            |
| last_login             | NULL               | NULL            |
| last_activity          | NULL               | NULL            |
| deleted_at             | NULL               | NULL            |
| iban                   | utf8               | utf8_general_ci |
+------------------------+--------------------+-----------------+
15 rows in set (0.003 sec)

MariaDB [(none)]> SELECT column_name, character_set_name, collation_name from information_schema.columns WHERE table_schema='NAME_OF_FOODCOOP' AND table_name = 'mail_delivery_status';
+-----------------+--------------------+-----------------+
| column_name     | character_set_name | collation_name  |
+-----------------+--------------------+-----------------+
| id              | NULL               | NULL            |
| created_at      | NULL               | NULL            |
| email           | utf8               | utf8_unicode_ci |
| message         | utf8               | utf8_unicode_ci |
| attachment_mime | utf8               | utf8_unicode_ci |
| attachment_data | NULL               | NULL            |
+-----------------+--------------------+-----------------+
6 rows in set (0.040 sec)
```
The relevant part for this bug is the `_ci` suffix. Let us discuss the `utf8` vs `utf8mb4` issue somewhere else.

**Comment by wvengen** [comment]
Wow, good debugging, thanks!

**Comment by RayOei** [comment]
@yksflip Isn't this solved by now? That particular code is not even present any more in `app/views/admin/users/_users.html.haml`

**Comment by JuliusR** [comment]
If the code is not present in the view any more then this particular problem is gone. I did not check it myself. 

Please note that the underlying problem was an inconsistent behavior when comparing e-mail addresses: Some code paths used case-sensitive comparisons, while other code paths used case-insensitive comparisons. This underlying problem might still exist.

However, the following issue comment on rails' official GitHub project suggests that the underlying problem is gone in the edge version as of December 2024: https://github.com/rails/rails/issues/31445#issuecomment-2543906272.
